Setono\SyliusRedirectPlugin\Model\Redirect:
    constraints:
        - Setono\SyliusRedirectPlugin\Validator\Constraints\InfiniteLoop:
            groups: ['sylius']
        - Setono\SyliusRedirectPlugin\Validator\Constraints\Source:
            groups: ['sylius']

    properties:
        source:
            - NotBlank:
                groups: ['sylius']
            - NotIdenticalTo:
                propertyPath: destination
                message: setono_sylius_redirect.form.errors.source_must_not_equal_destination
                groups: ['sylius']
        destination:
            - NotBlank:
                groups: ['sylius']
