Setono\SyliusRedirectPlugin\Model\Redirect:
    properties:
        source:
        - NotBlank:
              groups: ['sylius']
        - Setono\SyliusRedirectPlugin\Validator\Constraints\Source:
        destination:
        - NotBlank:
              groups: ['sylius']
        -   Setono\SyliusRedirectPlugin\Validator\Constraints\InfiniteLoop:
                groups: ['sylius']
